<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\InternHub.Domain\InternHub.Domain.csproj" />
    <ProjectReference Include="..\InternHub.Infrastructure\InternHub.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>

  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
